<?php

function groceries_menu() {
    $items = array();
    $items['groceries_list'] = array(
        'title' => 'My Groceries',
        'access callback' => TRUE,
        'page callback' => 'groceries_display',
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function groceries_display() {
    $grocery_list = array(
            'eggs' => array(
                'price' => 3.20,
                'quantity' => 1,
                'expired' => FALSE,
            ),
            'milk' => array(
                'price' => 2.20,
                'quantity' => 2,
                'expired' => TRUE,
            ),
            'bread' => array(
                'price' => 4,
                'quantity' => 5,
                'expired' => TRUE,
            ),
        );
    $app = '';
    foreach ($grocery_list as $grocery_list_item_name => $grocery_list_item_value) {

        $app = $app.'<h3>' . $grocery_list_item_name . '</h3>
            <ul>
                <li>'.$grocery_list[$grocery_list_item_name]['price'].'</li>
                <li>'. $grocery_list[$grocery_list_item_name]['quantity'].'</li>
                </ul>';
    }
    return $app;

}
