<?php
function favorites_menu(){
        $favorites = favorites_list();
        $items = array();
        foreach($favorites as $favorite_key=>$favorite_value){
            $items['favorites/'. $favorite_key] = array(
                'title'=> $favorite_key,
                'access callback'=> TRUE,
                'page callback'=> "favorites",
                'page arguments'=> array($favorite_key, $favorite_value),
                'type'=> MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function favorites_list(){
    $favorites = array(
        'Movies' => array("Gladiator", "Usual Suspects", "Clockwork Orange"),
        'Songs' => array("All Along the Watchtower", "You Belong With Me", "Purple Rain"),
        'Books' => array("The Chrysalids", "You Are Not So Smart", "The Happiness Trap"),
     );

    return $favorites;
}

function favorites($args){
    var_dump($args);
    var_dump($favorite_key);
    return 'hi;'
}
