<?php
function favorites_menu(){
        $favorites = favorites_list();
        $items = array();
        foreach($favorites as $favorite_key=>$favorite_value){
            $items['favorites/'. $favorite_key] = array(
                'title'=> $favorite_key,
                'access callback'=> TRUE,
                'page callback'=> "favorites",
                'page arguments'=> array(1),
                'type'=> MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function favorites_list(){
    $favorites = array(
        'Movies' => array("Gladiator", "Usual Suspects", "Clockwork Orange"),
        'Songs' => array("All Along the Watchtower", "You Belong With Me", "Purple Rain"),
        'Books' => array("The Chrysalids", "You Are Not So Smart", "The Happiness Trap"),
     );

    return $favorites;
}

function favorites($args){
    $app = '<ul>';
    $favorites = favorites_list();
    foreach ($favorites as $favorite_key => $favorite_value) {
        if ($favorite_key === $args) {
            foreach($favorite_value as $value) {
                $app .= "<li>$value</li>";
            }
        }
    }
    $app .= '</ul>';
    return $app;
}
