<?php
function cards_menu(){
        $friends = friend_list();
        $items = array();
        foreach($friends as $friend){
            $items['cards/'. $friend] = array(
                'title'=> $friend,
                'access callback'=> TRUE,
                'page callback'=> "cards",
                'page arguments'=> array(1),
                'type'=> MENU_NORMAL_ITEM,
        );
    }
    return $items;
}

function friend_list(){
    $friends = array("Tim", "Irma", "Frank");
    return $friends;
}

function cards($args){
        var_dump($args);
        $friend = $args;
            return 'hi ' . $friend;
        }
