<?php
    function pets_menu(){
        $items = array();
        $items['pet_display'] = array(
            'title' => 'Favorite Pet',
            'page callback'=> 'pet_info_display',
            'access callback' => TRUE,
            'type' => MENU_NORMAL_ITEM,
        );
        return $items;
    }

    function pet_info_display(){
        return '<h2> This was Fluffy</h2>
                <p> She was a good dog.</p>
                <img src="sites/all/modules/mycustommenu_items/pets/fluffy.jpg" alt="Fluffy Picture">
                <a href="/dogs">More information about Dogs</a>';
    }
